/**
 * Дерево категорий площадки: разделы и подкатегории.
 * Порядок в массивах задаёт `position`; `name` пишется в `categories.name`,
 * `nameEn` пока в БД не хранится.
 *
 * Slug уникален во всём дереве: у подкатегорий он начинается с раздела
 * (`antiques-silver`), кроме «Коллекционного» — его подкатегории основные
 * для площадки и сохраняют короткие slug из текущего сида (`coins`, `stamps`).
 */
export type CategoryNode = {
  slug: string;
  name: string;
  nameEn: string;
  children?: CategoryNode[];
};

export const CATEGORY_TREE: CategoryNode[] = [
  {
    slug: "antiques",
    name: "Антиквариат и искусство",
    nameEn: "Antiques and Art",
    children: [
      { slug: "antiques-asian", name: "Азиатская антика", nameEn: "Asian antiques" },
      { slug: "antiques-furniture", name: "Антикварная мебель", nameEn: "Antique furniture" },
      { slug: "antiques-weapons", name: "Антикварное оружие", nameEn: "Antique weapons" },
      { slug: "antiques-weapon-parts", name: "Антикварное оружие — запчасти", nameEn: "Antique weapon parts" },
      { slug: "antiques-books", name: "Антикварные книги", nameEn: "Antiquarian books" },
      { slug: "antiques-antiquity", name: "Античность", nameEn: "Antiquity" },
      { slug: "antiques-prints", name: "Гравюры, карты, плакаты", nameEn: "Prints, maps and posters" },
      { slug: "antiques-decorative", name: "Декоративное искусство", nameEn: "Decorative arts" },
      { slug: "antiques-europe", name: "Европа", nameEn: "Europe" },
      { slug: "antiques-painting", name: "Живопись, графика", nameEn: "Painting and graphics" },
      { slug: "antiques-icons", name: "Иконы", nameEn: "Icons" },
      { slug: "antiques-household", name: "Кухонная и домашняя утварь", nameEn: "Kitchen and household utensils" },
      { slug: "antiques-castings", name: "Литьё", nameEn: "Castings" },
      { slug: "antiques-medicine", name: "Медицина", nameEn: "Medicine" },
      { slug: "antiques-copper", name: "Медь", nameEn: "Copper" },
      { slug: "antiques-metal", name: "Металл", nameEn: "Metal" },
      { slug: "antiques-musical", name: "Музыкальные инструменты, приборы", nameEn: "Musical instruments and devices" },
      { slug: "antiques-folk-art", name: "Народное искусство", nameEn: "Folk art" },
      { slug: "antiques-lighting", name: "Осветительные приборы", nameEn: "Lighting" },
      { slug: "antiques-records", name: "Пластинки", nameEn: "Records" },
      { slug: "antiques-interior", name: "Предметы интерьера", nameEn: "Interior items" },
      { slug: "antiques-reproductions", name: "Предметы под старину", nameEn: "Antique-style items" },
      { slug: "antiques-silver", name: "Серебро", nameEn: "Silver" },
      { slug: "antiques-medieval", name: "Средневековье", nameEn: "Middle Ages" },
      { slug: "antiques-glass", name: "Стекло и хрусталь", nameEn: "Glass and crystal" },
      { slug: "antiques-souvenirs", name: "Сувениры", nameEn: "Souvenirs" },
      { slug: "antiques-textiles", name: "Текстиль, нитки", nameEn: "Textiles and thread" },
      { slug: "antiques-instruments", name: "Техника, приборы", nameEn: "Technology and instruments" },
      { slug: "antiques-porcelain", name: "Фарфор, фаянс, керамика", nameEn: "Porcelain, faience and ceramics" },
      { slug: "antiques-clocks", name: "Часы", nameEn: "Clocks and watches" },
      { slug: "antiques-ethnography", name: "Этнография", nameEn: "Ethnography" },
      { slug: "antiques-jewelry", name: "Ювелирные изделия", nameEn: "Jewelry" },
      { slug: "antiques-other", name: "Разное", nameEn: "Miscellaneous" },
    ],
  },
  {
    slug: "vintage",
    name: "Винтаж",
    nameEn: "Vintage",
    children: [
      { slug: "vintage-accessories", name: "Аксессуары", nameEn: "Accessories" },
      { slug: "vintage-perfume", name: "Винтажная парфюмерия и косметика", nameEn: "Vintage perfume and cosmetics" },
      { slug: "vintage-metal", name: "Изделия из металла", nameEn: "Metalware" },
      { slug: "vintage-footwear", name: "Обувь", nameEn: "Footwear" },
      { slug: "vintage-print", name: "Печатные издания", nameEn: "Printed matter" },
      { slug: "vintage-glass", name: "Стекло", nameEn: "Glass" },
      { slug: "vintage-textiles", name: "Текстиль", nameEn: "Textiles" },
      { slug: "vintage-electronics", name: "Техника", nameEn: "Appliances and electronics" },
      { slug: "vintage-jewelry", name: "Украшения", nameEn: "Jewelry" },
      { slug: "vintage-porcelain", name: "Фарфор", nameEn: "Porcelain" },
      { slug: "vintage-other", name: "Другое", nameEn: "Other" },
    ],
  },
  {
    slug: "collectibles",
    name: "Коллекционное",
    nameEn: "Collectibles",
    children: [
      { slug: "cans-bottles", name: "Банки, бутылки, пробки, кружки", nameEn: "Cans, bottles, caps and mugs" },
      { slug: "banknotes", name: "Банкноты и боны", nameEn: "Banknotes and paper money" },
      { slug: "tickets", name: "Билеты", nameEn: "Tickets" },
      { slug: "militaria", name: "Военная атрибутика", nameEn: "Militaria" },
      { slug: "documents", name: "Документы", nameEn: "Documents" },
      { slug: "christmas-decorations", name: "Ёлочные украшения", nameEn: "Christmas decorations" },
      { slug: "chewing-gum", name: "Жевательная резинка", nameEn: "Chewing gum" },
      { slug: "toys-games", name: "Игрушки и игры", nameEn: "Toys and games" },
      { slug: "calendars", name: "Календари", nameEn: "Calendars" },
      { slug: "covers", name: "Конверты и почтовые карточки", nameEn: "Covers and postal cards" },
      { slug: "replicas", name: "Копии или реплики", nameEn: "Copies and replicas" },
      { slug: "literature", name: "Литература", nameEn: "Literature" },
      { slug: "stamps", name: "Марки", nameEn: "Stamps" },
      { slug: "models", name: "Модели", nameEn: "Models" },
      { slug: "coins", name: "Монеты", nameEn: "Coins" },
      { slug: "medals", name: "Награды, жетоны, медали, значки", nameEn: "Awards, tokens, medals and badges" },
      { slug: "postcards", name: "Открытки", nameEn: "Postcards" },
      { slug: "plastic-cards", name: "Пластиковые карты", nameEn: "Plastic cards" },
      { slug: "signumanistics", name: "Сигнуманистика", nameEn: "Signumanistics" },
      { slug: "sports", name: "Спортивное коллекционирование", nameEn: "Sports collectibles" },
      { slug: "photos", name: "Фотографии", nameEn: "Photographs" },
      { slug: "fumophilia", name: "Фумофилия", nameEn: "Fumophilia" },
      { slug: "labels", name: "Этикетки", nameEn: "Labels" },
      { slug: "collectibles-other", name: "Другое", nameEn: "Other" },
    ],
  },
  {
    slug: "handmade",
    name: "Сделано своими руками",
    nameEn: "Handmade",
    children: [
      { slug: "handmade-batik", name: "Батик", nameEn: "Batik" },
      { slug: "handmade-trinkets", name: "Безделушки", nameEn: "Trinkets" },
      { slug: "handmade-beads", name: "Бисер", nameEn: "Beadwork" },
      { slug: "handmade-bottles", name: "Бутылки", nameEn: "Bottles" },
      { slug: "handmade-woodburning", name: "Выжигание по дереву", nameEn: "Wood burning" },
      { slug: "handmade-embroidery", name: "Вышивка", nameEn: "Embroidery" },
      { slug: "handmade-knitting", name: "Вязание", nameEn: "Knitting" },
      { slug: "handmade-graphics", name: "Графика", nameEn: "Graphics" },
      { slug: "handmade-painting", name: "Живопись", nameEn: "Painting" },
      { slug: "handmade-leather", name: "Изделия из кожи", nameEn: "Leather goods" },
      { slug: "handmade-interior", name: "Интерьер", nameEn: "Interior" },
      { slug: "handmade-ceramics", name: "Керамика", nameEn: "Ceramics" },
      { slug: "handmade-books", name: "Книги", nameEn: "Books" },
      { slug: "handmade-lace", name: "Кружево", nameEn: "Lace" },
      { slug: "handmade-dolls", name: "Куклы и игрушки", nameEn: "Dolls and toys" },
      { slug: "handmade-macrame", name: "Макраме", nameEn: "Macrame" },
      { slug: "handmade-metal", name: "Металл", nameEn: "Metal" },
      { slug: "handmade-mosaic", name: "Мозаика", nameEn: "Mosaic" },
      { slug: "handmade-clothing", name: "Одежда", nameEn: "Clothing" },
      { slug: "handmade-postcards", name: "Открытки", nameEn: "Postcards" },
      { slug: "handmade-papier-mache", name: "Папье-маше", nameEn: "Papier-mâché" },
      { slug: "handmade-sculpting", name: "Пластика", nameEn: "Sculpting" },
      { slug: "handmade-patchwork", name: "Пэчворк", nameEn: "Patchwork" },
      { slug: "handmade-woodcarving", name: "Резьба по дереву", nameEn: "Wood carving" },
      { slug: "handmade-decorative-painting", name: "Роспись", nameEn: "Decorative painting" },
      { slug: "handmade-glass", name: "Стекло", nameEn: "Glass" },
      { slug: "handmade-souvenirs", name: "Сувениры", nameEn: "Souvenirs" },
      { slug: "handmade-bags", name: "Сумки", nameEn: "Bags" },
      { slug: "handmade-supplies", name: "Товары для творчества", nameEn: "Craft supplies" },
      { slug: "handmade-jewelry", name: "Украшения", nameEn: "Jewelry" },
      { slug: "handmade-polymer-clay", name: "Фимо", nameEn: "Polymer clay" },
      { slug: "handmade-other", name: "Другое", nameEn: "Other" },
    ],
  },
  {
    slug: "business",
    name: "Для бизнеса",
    nameEn: "For Business",
    children: [
      { slug: "business-banking", name: "Банковское оборудование", nameEn: "Banking equipment" },
      { slug: "business-vending", name: "Вендинговое оборудование", nameEn: "Vending equipment" },
      { slug: "business-veterinary", name: "Ветеринария", nameEn: "Veterinary" },
      { slug: "business-accessories", name: "Деловые аксессуары", nameEn: "Business accessories" },
      { slug: "business-materials", name: "Материалы и сырьё", nameEn: "Materials and raw materials" },
      { slug: "business-medical", name: "Медицинское оборудование", nameEn: "Medical equipment" },
      { slug: "business-office", name: "Офисное оборудование", nameEn: "Office equipment" },
      { slug: "business-tanning", name: "Солярии", nameEn: "Tanning beds" },
      { slug: "business-machinery", name: "Станки и оборудование", nameEn: "Machinery and equipment" },
      { slug: "business-retail", name: "Торговое оборудование", nameEn: "Retail equipment" },
      { slug: "business-packaging", name: "Упаковка и оборудование", nameEn: "Packaging and equipment" },
      { slug: "business-other", name: "Разное", nameEn: "Miscellaneous" },
    ],
  },
];
